{%- from "prometheus/map.jinja" import server with context %}

{%- set alerts = {} %}
{%- set recordings = {} %}

{%- for node_name, node_grains in salt['mine.get']('*', 'grains.items').iteritems() %}
  {%- set server_grain = node_grains.get('prometheus', {}).get('server', {}) %}
  {%- for recordingname, recording in server_grain.get('recording', {}).iteritems() %}
    {%- do recordings.update({recordingname: recording}) %}
  {%- endfor %}
{%- endfor %}

{%- set recordings = salt['grains.filter_by']({'default': recordings}, merge=server.get('recording', {})) %}

{%- for recordingname, recording in recordings.iteritems() %}
  {%- if recording.get('enabled', True) %}
    {{ recordingname }} = {{ recording.query }}
  {%- endif %}
{%- endfor %}

{%- for node_name, node_grains in salt['mine.get']('*', 'grains.items').iteritems() %}
  {%- set server_grain = node_grains.get('prometheus', {}).get('server', {}) %}
  {%- for alertname, alert in server_grain.get('alert', {}).iteritems() %}
      {%- do alerts.update({alertname: alert}) %}
  {%- endfor %}
{%- endfor %}

{%- set alerts = salt['grains.filter_by']({'default': alerts}, merge=server.get('alert', {})) %}

{%- for alertname, alert in alerts.iteritems() %}
  {%- if alert.get('enabled', True) %}
    ALERT {{ alertname }}
      IF {{ alert.if }}
      {%- if alert.for is defined %}FOR {{ alert.for }}{%- endif %}
      {%- if alert.labels is defined %}
      LABELS {
        {%- for name, value in alert.labels.iteritems() %}
        {{ name }} = "{{ value }}"{%- if not loop.last %},{%- endif %}
        {%- endfor %}
      }
      {%- endif %}
      {%- if alert.annotations is defined %}
      ANNOTATIONS {
        {%- for name, value in alert.annotations.iteritems() %}
        {{ name }} = "{{ value }}"{%- if not loop.last %},{%- endif %}
        {%- endfor %}
      }
      {%- endif %}
  {%- endif %}
{%- endfor %}
